### ISSUE TITLE
setPosition of a Tab

### ISSUE THREAD

**Issue by elademir** [sojamo/controlp5#11]
Hi Sojamo, I would like to change the position of a Tab controller from your library, Is this possible?.
By default the first Tab is put on (0,0) position, and the next tab on right the first and so on. Can I change this?. If I use .setPosition, it is changes the position of the objects inside the tab but not the position of the tab itself.

regards!

**Comment by sojamo** [comment]
Hello elademir, I am afraid you can't change that out of the box, but you could create your own custom tabs using buttons?

**Comment by werty37** [comment]
@sojamo , Can this be a feature request for the next release if possible? I am also looking for the same functionality of moving tab positions.
