### ISSUE TITLE
Save/Load properties of ScrollableList - Bug

### ISSUE THREAD

**Issue by b3nson** [sojamo/controlp5#12]
Trying to save and load properties of a ScrollableList results in "java.lang.NoSuchMethodException" (caught ones = no program-termination)

**Saving** ScrollableList-Properties (to json) actually works, but following debug-message appears:
```java
SEVERE: java.lang.NoSuchMethodException: controlP5.ScrollableList.getListBoxItems()
```
**Loading** back this property won`t either set the (internal) value of the ScrollableList, nor change the corresponding item visually. Following debug-message appears:
```java
java.lang.NoSuchMethodException: controlP5.ScrollableList.setValue(float)
```

#### Code Example
Press <kbd>1</kbd> to print current value, <kbd>2</kbd> to save properties, <kbd>3</kbd> to load back saved properties.
```java
import controlP5.*;
import java.util.*;

ControlP5 cp5;

void setup() {
  size(400, 400);
  cp5 = new ControlP5(this);
  List l = Arrays.asList("a", "b", "c", "d", "e", "f", "g", "h");

  cp5.addScrollableList("dropdown")
     .setPosition(100, 100)
     .setSize(200, 100)
     .setBarHeight(20)
     .setItemHeight(20)
     .addItems(l)
     .setType(ScrollableList.LIST) // or DROPDOWN
     ;
}

void draw() {
  background(240);
}

void keyPressed() {
  switch(key) {
    case('1'):
        println("currentValue: " +cp5.get(ScrollableList.class, "dropdown").getValue());
    break;
    case('2'):
        cp5.saveProperties("hello.json");
    break;
    case('3'):
        cp5.loadProperties("hello.json");
    break;
  }
}
```

**Comment by b3nson** [comment]
Hey Andreas,
thanks for the quick update!
But the issue is not yet fixed completely...

**Loading** from saved Properties **works**, but saving results in an empty entry ("{}") in the JSON-File.
I think the following should fix the issue:

[ControlP5Legacy.java | Line 297](http://github.com/sojamo/controlp5/blob/master/src/controlP5/ControlP5Legacy.java#L297)
```diff
- myController.registerProperty( "items" ).registerProperty( "value" );
+ myController.registerProperty( "value" );
```

Thanks for your efforts,
best,
benjamin.

**Comment by sojamo** [comment]
strange, worked for me with [release 2.2.5](https://github.com/sojamo/controlp5/releases/tag/v2.2.5)  of the library - I have removed the "items" property now and updated the .zip file for release 2.2.5. This has been successfully tested with processing 2.2.1, osx 10.10 and the example given above.

**Comment by b3nson** [comment]
arrrghh, damn it, you are right!!
it also worked with the first fix! 
(i had a slightly modified test-scenario in the meantime, where i didn't create the ScrollableListBox with `cp5.addScrollableListBox(...)`, but with its constructor..., in that case the fix didn't work)

**Now both fixes seem to work!**
Tested with Processing 2.2.1 and 3.0a5 on osx 10.10

Thanks a lot!
