### ISSUE TITLE
Suggestion for ScrollableList: getItemHover()

### ISSUE THREAD

**Issue by b3nson** [sojamo/controlp5#14]
#### Find out which list-item of a ScrollableList is currently hovered
In the old/deprecated `DropdownList` one could trigger stuff by just **hovering** individually list-items, because you could find out over which particular `ListBoxItem` you were currently hovering through the `cp5.isMouseOver(ListBoxItem xy)` respectively `cp5.getWindow().getMouseOverList()` functionality.

In the new `ScrollableList` this is not possible anymore, because list-items are implemented differently and are not of type `Controller` anymore.

Internally in `ScrollableList` there is the field `protected int itemHover;` which gets tracked throughout the enter/hover/leave-process to highlight the hovered list-entry.

So an easy solution would be to make this field visible from "outer space" through providing a getter for it:
**`public int getHoverIndex()`** or `getItemHover()` 
~~(returns null if ScrollableList is currently not hovered)~~ (internally itemHover is -1 when not hovered, so -1)

What do you think??
Wanted/Planned functionality?

Greetings, benjamin.

**Comment by sojamo** [comment]
let me put this on the todo list for now. meanwhile the following might help:

``` java
import controlP5.*;
import java.util.*;

ControlP5 cp5;


void setup() {
  size(500,500);
  cp5 = new ControlP5(this);
  
  ScrollableListExtended s = new ScrollableListExtended( cp5, "dropdown");
  s.registerProperty( "value" );
  s.addItems(Arrays.asList("a", "b", "c", "d", "e", "f", "g", "h","i","j","k","l","m"));
  s.setPosition(100,100).setHeight(100).setType(ScrollableList.LIST);
}

void draw() {
  background(200);
}


class ScrollableListExtended extends ScrollableList {
  
  ScrollableListExtended( ControlP5 theControlP5, String theName ) {
    super(theControlP5, theName);
  }
  
  public ScrollableListExtended setValue( float theValue ) {
    super.setValue(theValue);
    return this;
  }
  
  void onMove() {
    super.onMove();
    checkHover();
  }
  
  void checkHover() {
    println("item hover:", itemHover);
  }
}


void keyPressed() {
  switch(key) {
    case('1'):
        println("currentValue: " +cp5.get(ScrollableList.class, "dropdown").getValue());
    break;
    case('2'):
        cp5.saveProperties("hello.json");
    break;
    case('3'):
        cp5.loadProperties("hello.json");
    break;
  } 
}
```

**Comment by b3nson** [comment]
:thumbsup: thanks!
