### ISSUE TITLE
Control Matrix Stepping Value

### ISSUE THREAD

**Issue by ghost** [sojamo/controlp5#140]
Is there a built in function to control the steps reading velocity of a Matrix?
What I mean is control the speed of the line that runs the matrix from left to right
I would very much like to control that velocity!
Something like 
CP5.get(Matrix.class, "matrixName").velocityOfLine;

Is there a way to do this?
(also would be cool to change width of that line it's too tiny)
Best, Luis

**Comment by sojamo** [comment]
Hi,

you can use `setInterval(millis)` to control timing/velocity.
`CP5.get(Matrix.class, "matrixName").setInterval(1000); // set the time intervals to 1000milliseconds`

In regard to the width of the line, I am afraid it is hard coded, 1px.

**Comment by ghost** [comment]
Thank you sojamo!
Best, Luis
