### ISSUE TITLE
Use Radio buttons and Sliders together to manipulate geometries

### ISSUE THREAD

**Issue by liuzmm** [sojamo/controlp5#15]
Hi sojamo,
I'm usign a ControlP5 interface to handle IGeo geometries and I'm trying to use buttons and sliders together to manipulate 3 curves. I have two sliders for each one, which allow me to move the curve in X and Y direction, and a button for each curve, to rotate it 180°. The sliders are working in the right way, but I'm having some troubles with the buttons. I'm trying to adapt the Button example to my sketch but if I press the button I'm able to rotate the curve just one time, after the first time the button is not working (I need to rotate it everytime I press). 
Which is the right way to use this controllers together?
Thanks in advance!

**Comment by sojamo** [comment]
Hi, I think this is more of a processing specific question and I see you have started a thread in the processing forum as well. closing this issue.
