### ISSUE TITLE
IllegalAccessError in class controlP5.BitFont in Processing 3.0a11

### ISSUE THREAD

**Issue by DEHiCKA** [sojamo/controlp5#16]
IllegalAccessError: tried to access field processing.core.PFont.size from class controlP5.BitFont

The processing library has updated and do not allow access the field directly.

**Comment by sojamo** [comment]
which version of controlP5 are you using? the version number is printed into the console when starting a sketch using this library.

**Comment by sojamo** [comment]
please see [processing issue 3519](https://github.com/processing/processing/issues/3519)
