### ISSUE TITLE
Processing 3 support

### ISSUE THREAD

**Issue by codingjoe** [sojamo/controlp5#25]
Hi @sojamo,

I was wondering if you could contribute in any way to add Processing 3 support.

I'm the creator of [MusicBeam](http://musicbeam.zepplab.net/) which highly depends on ControlP5. I could ask my users for contributions as well, if needed.

Cheers,
Joe

**Comment by sojamo** [comment]
Hi, the current version of controlP5 (2.2.5 as of writing this) is compatible with processing 3 and has been tested on OS X. You can install it via the library manager or by manually copying the library into the libraries folder. If you run or run into any issues, please let me know.

**Comment by codingjoe** [comment]
Thanks!
