### ISSUE TITLE
Hit area on controls is borked when using translate()

### ISSUE THREAD

**Issue by EJTH** [sojamo/controlp5#27]
If a control is moved with translate() the cursor hit detection doesn't use the actual position of the control.

**Comment by sojamo** [comment]
transformations such as translate, rotate, size are not supported and will clash with mouse input parameters. In case you are using transformations inside your code, add `pushMatrix()` at the beginning of your `draw()` routine and `popMatrix()` at the end to not affect the rendering and input behavior of controlP5.
