### ISSUE TITLE
 controlp5 Missing 'author' from library

### ISSUE THREAD

**Issue by GamerGoblin** [sojamo/controlp5#30]
Hello There,

I hope you're well and may be able to help with an issue I'm having with the ControlP5 library. I've been playing around with an Adafruit Trinket and some Neopixels. But I can't actually ever seem to successfully upload a sketch to the microcontroller on the Trinket, to drive the Neopixels.

I keep getting the following error message, right before it is about to complete the upload.

"Documents\Arduino\libraries\controlP5: Missing 'author' from library"

I'm not sure why there would be a missing 'author' from the library or what that exactly means, but I was hoping someone could shed some light on this issue or know of a workaround/fix.

Kind Regards,

Michael B

**Comment by sojamo** [comment]
Hi, controlP5 is a Processing library and hence can't be uploaded to a hardware component like the Trinket from the Arduino environment. Maybe you want to control a Trinket from a GUI software? Then you could for example send data from a software to the hardware using serial communication.

**Comment by GamerGoblin** [comment]
A very very stupid question. Apologies for wasting your time mate.

Thanks for the quick response though
