### ISSUE TITLE
controlP5.js

### ISSUE THREAD

**Issue by nkint** [sojamo/controlp5#35]
I read that it is on hold.. is there any kind of material online (repo or something else?)
I need a simple gui with p5.js and if there is something on hold I can try to use it anyway.. Maybe help to improve it?

**Comment by sojamo** [comment]
ControlP5 for js will be unlikely, I did get some controllers going for processing.js but wouldn't consider the state of the code to be releasable. controlP5 for p5.js is also unlikely, I would rather start a gui library from scratch, this is quite likely to happen.

**Comment by GoToLoop** [comment]
If starting another GUI from scratch, it'd be so nice to have consistent API across Processing flavors: Java Mode, JS Mode & p5.js.  For inspiration, there's a very good JS canvas-based GUI library called Zebra:

https://GitHub.com/barmalei/zebra
http://www.ZebKit.com
