### ISSUE TITLE
Cannot get Radiobutton from within a group with the getController() method

### ISSUE THREAD

**Issue by a-cordier** [sojamo/controlp5#4]
Hi,

Type off RadioButton is ControllerGroup and for this reason the widget cannot be retrieved by name from within a group with "getController(String name): Controller"

Retrieving a ControllerInterface object and then casting it to RadioButton results in getting a a null object when using the getController(String name) method on the group.

Hope this is clear enough

**Comment by chrisb1978** [comment]
I'm having the same problem as @a-cordier - what's the proper way to do this?
(on 2.2.6)
thanks!
