### ISSUE TITLE
.bringToFront() to a group in an Accordion pushes it to the bottom

### ISSUE THREAD

**Issue by cladelpino** [sojamo/controlp5#44]
I modified very slightly the code of the example so it can be seen what I'm talking about. I guess this isn't intentional behaviour so I open this issue.

Any other way to bring the ScrollableList to front in this situation ? Changing the order in which groups are added won't do for me since my idea for my GUI is to have accordion in groups like "floating" widgets. 

[accordionbringToFrontBug.zip](https://github.com/sojamo/controlp5/files/96772/accordionbringToFrontBug.zip)

**Comment by sojamo** [comment]
I would say this is a special case, I had a quick look into it, but the way the accordion is designed, I won't be fixing it.

**Comment by cladelpino** [comment]
Yes, we looked at it too, and its very deep in the design of accordion. We went around it but still wanted to notify. Accordion + Dropdown = this issue. Thanks for replying !

**Comment by sojamo** [comment]
ok, do you want to close the issue?

**Comment by doctea** [comment]
Just found this ticket while searching for a solution to the problem where ScrollableList dropdowns appear 'underneath' the Accordion headers (and other UI elements).  

I'm running into the same problem, what suggested workarounds are there to enable displaying of scrollablelist dropdown over the top of an accordion without breaking the accordion order?
