### ISSUE TITLE
bad value in Color picker

### ISSUE THREAD

**Issue by mulholland77** [sojamo/controlp5#52]
controlp5 2.2.5,
Processing 3.0.2

I wonder if it's due to my recent Processing update but in colorPicker exemple
controlEvent and picker don't return the same value. 
the issue is with picker.
 
In extrem situation, one say 255 and the other 0 :/

![capture d ecran 2016-02-20 a 14 42 28](https://cloud.githubusercontent.com/assets/17247746/13197000/6c018842-d7e0-11e5-83d8-6ab4d0c8bb3d.png)

**Comment by sojamo** [comment]
fixed with version 2.2.6
