### ISSUE TITLE
ControlP5frame example code does not compile

### ISSUE THREAD

**Issue by PavelSto** [sojamo/controlp5#56]
I am using processing-3.0.2 on Linux.
When I click:  File > examples > contributed libraries > ControlP5 > extra > ControlP5frame,
there are 2 errors:
Line 45:  f.add(p):  The function "add()" expects parameters like: "add(Component)"
Line 46:  p.init():     The function "init()" does not exist

**Comment by sojamo** [comment]
Hi, you might want to check issue #17

**Comment by sojamo** [comment]
controlP5frame example updates with release 2.2.6
