### ISSUE TITLE
Set toUpperCase() globally

### ISSUE THREAD

**Issue by fukuchi** [sojamo/controlp5#60]
Setting toUpperCase(false) for every labels is annoying. Plus, some labels are unable to touch from user's program (e.g. labels of ScrollableList). How about adding global isToUpperCase flag? For example, adding a class variable to Label class as following:

```
public class Label implements CDrawable {
        ...
        public static boolean isToUpperCaseDefault = true;
        protected boolean isToUpperCase = isToUpperCaseDefault;
        ...
        public static void setUpperCaseDefault( boolean theValue ) {
                isToUpperCaseDefault = theValue;
        }
        ...
}
```

This isn't perfect solution because the class method above cannot change exiting labels' isToUpperCase.

Your comments are welcome.

**Comment by sojamo** [comment]
implemented with 2.2.6

``` processing

Label.setUpperCaseDefault(false);
cp5 = new ControlP5(this);
cp5.setFont(createFont("Arial",12));

```
