### ISSUE TITLE
"controlP5" and standard "net.java.games.input" library both use 'controller' classes?

### ISSUE THREAD

**Issue by marccolemont** [sojamo/controlp5#62]
I have an issue where I have working code with the net.java.games.input library that gets corrupted when adding the controlP5 library to add GUI.

Here is some small code which shows the problem: 
Both seem to use a class with 'controller' which conflicts.
Currently stuck, no idea how to work around it.
The error message in Processing 3: The type Controller is ambiguous

// Start Code
import controlP5.*; // When adding this library code doesn't work anymore
import net.java.games.input.*;
import net.java.games.input.Event;
import net.java.games.input.EventQueue;

HashMap spaceNavigator = new HashMap();

void setup()
{
  size(500, 500, P3D);

  // Print the available controllers
  listControllers();
  // Initialize the right controller
  initController(2);
}

void draw()
{
  background(0);

  // Update controller values and put them in a HashMap
  // x, y, z, rx, ry, rz, b0, b1
  spaceNavigator = updateController();

  fill(255);
  text("x: " + spaceNavigator.get("x"), 20, 20);
  text("y: " + spaceNavigator.get("y"), 20, 40);
  text("z: " + spaceNavigator.get("z"), 20, 60);
  text("rx: " + spaceNavigator.get("rx"), 20, 80);
  text("ry: " + spaceNavigator.get("ry"), 20, 100);
  text("rz: " + spaceNavigator.get("rz"), 20, 120);
  text("b0: " + spaceNavigator.get("b0"), 20, 140);
  text("b1: " + spaceNavigator.get("b1"), 20, 160);
  
  // Draw a box with the received values
  spacebox();
}

void spacebox()
{

  float mt = 40.0;
  float mr = 1.0;
  float xx = (Float)spaceNavigator.get("x")*10;
  float yy = (Float)spaceNavigator.get("y")*10;
  float zz = (Float)spaceNavigator.get("z")*10;
  float rx = (Float)spaceNavigator.get("rx")*10;
  float ry = (Float)spaceNavigator.get("ry")*10;
  float rz = (Float)spaceNavigator.get("rz")*10;
  float b0 = (Float)spaceNavigator.get("b0")*10;
  float b1 = (Float)spaceNavigator.get("b1")*10;
  
  

  pushMatrix();

  fill(100);
  translate(width/2, height/2);
  translate(xx * mt, yy * mt, zz * mt);
  rotateX(rx * mr);
  rotateY(ry * mr);
  rotateZ(rz * mr);

  box(150, 150, 150);

  popMatrix();
}

Controller Nav;
ControllerEnvironment ce;
HashMap<String,Float> ct = new HashMap<String,Float>();

void initController(int id)
{
  Nav = ce.getControllers()[id];
  
  // Initial values
  ct.put("x", 0.0);
  ct.put("y", 0.0);
  ct.put("z", 0.0);
  ct.put("rx", 0.0);
  ct.put("ry", 0.0);
  ct.put("rz", 0.0);
  ct.put("b0", 0.0);
  ct.put("b1", 0.0);
}

HashMap updateController()
{
  Nav.poll();
  EventQueue queue = Nav.getEventQueue();
  Event event = new Event();

  while (queue.getNextEvent (event))
  {
    Component comp = event.getComponent();

    if (comp.getName() == "x")
      ct.put("x", (float)event.getValue());
    else if (comp.getName() == "y")
      ct.put("z", (float)event.getValue()); //ok
    else if (comp.getName() == "z")
      ct.put("y", (float)event.getValue());
    else if (comp.getName() == "rx")
      ct.put("rx", -(float)event.getValue());
    else if (comp.getName() == "ry")
      ct.put("rz", -(float)event.getValue());
    else if (comp.getName() == "rz")
      ct.put("ry", -(float)event.getValue());
    else if (comp.getName() == "0")
      ct.put("b0", (float)event.getValue());
    else if (comp.getName() == "1")
      ct.put("b1", (float)event.getValue());
  }
  return ct;
}

void listControllers()
{
  ce = ControllerEnvironment.getDefaultEnvironment();

  Controller[] cs = ce.getControllers();

  if (cs.length == 0) {
    System.out.println("No controllers found");
    System.exit(0);
  }

  for (int i = 0; i < cs.length; i++)
    System.out.println(i + ". " +
      cs[i].getName() + ", " + cs[i].getType() );
}

// End Code

**Comment by sojamo** [comment]
There is a naming conflict since both controlP5 and net.java.games.input both implement a class with name Controller. to distinguish both from each other, use net.java.games.input.Controller when referring to a Controller from the net.java.games.input package. (to better read the code you have posted, could you code-format it? see the __insert code__ icon when editing/writing a comment.)

**Comment by marccolemont** [comment]
Hi Andreas,

I'll try that!
Thanks for your great libraries. 
Really helpfull tools. 

Thanks for your quick reply. 

Marc Colemont

**Comment by sojamo** [comment]
Hi, is the issue fixed? do you want to close this issue?

**Comment by marccolemont** [comment]
Yes you can close the ticket, thanks.
