### ISSUE TITLE
Image loading for controllers

### ISSUE THREAD

**Issue by SimonVHB** [sojamo/controlp5#64]
Hello,
I love the usage to load images for buttons, but today I found CP5 has a really hard time loading images with transparent parts (alpha values).
When I load the image in processing just with image() it works perfectly fine!

Greetings

**Comment by sojamo** [comment]
Hi, this works fine for me. circle on the left is a button, see code below. circle on the right is the same image but rendered with `image(PImage,x,y)`
<img width="312" alt="cp5-button-bg-transparent" src="https://cloud.githubusercontent.com/assets/81155/14772096/7e4492a0-0acc-11e6-89f8-732ce5800344.png">

``` processing
cp5.addButton("a").setImage(loadImage("button.png")).updateSize().setPosition(20,20);
// button.img is a png-24 image with transparent background
```

_(osx, p5 3.0.2, cp5 2.2.5, all renderers)_

**Comment by SimonVHB** [comment]
Hello, that's pretty strange that it does that for me then.
I took some pictures to show what happens:

`pauseBut = cp5.addBang("pauseGame")
                  .setPosition(10, hoogte-200) 
                  .setImage(pauseButton2)
                  .updateSize()
                  ;`

![bad imgae](https://cloud.githubusercontent.com/assets/16856776/14794026/2d460af4-0b22-11e6-8568-a68e3bf779d9.png)

`image(pauseButton2, 10, hoogte-200);`

![good image](https://cloud.githubusercontent.com/assets/16856776/14794078/680de8be-0b22-11e6-9316-7b7a1b5ee4eb.png)

pauseButton2 is a PImage that has the transparent borders. "breedte" and "hoogte" are variables I made that just gave the screensize in them.

(win10, p3 3.0.2, cp5 2.2.6)

**Comment by sojamo** [comment]
What image format are you using? gif or png-24? Could it be that the background in the first screenshot is not updated over time (inside  draw()) hence the transparent part of the image leaves these artefacts. could you share a runnable example that highlights the issue?

**Comment by SimonVHB** [comment]
The image format is a png. And the first screenshot is in the draw().
I have a function running that should change the picture when my mouse is over the button (with cp5.isMouseOver() ), but when I do that it like "grows" the border around the book.

I'll make a runnable example as fast as I can!

**Comment by sojamo** [comment]
any updates, otherwise I should close this issue soon.
