### ISSUE TITLE
Multiple windows in Processing (ControlP5)

### ISSUE THREAD

**Issue by smvwhite** [sojamo/controlp5#70]
I'm wanting to use a control window (ControlP5 library) with sliders to alter graphics on the main canvas.
I can do this with sliders on the main canvas, but for some reason, the test slider appears on the main canvas and there isn't any second window when using addControlWindow.

Thanks in advance for any help guys.

``import controlP5.*;

//Declare Controls ControlP5 controlP5; ControlWindow myControlWindow; //initialize control window Controller slider; //initialize slider

//Setup

void setup() { //Initalize Main Canvas size(1480, 360);

//Initialize ControlP5 and Control Window controlP5 = new ControlP5(this);

myControlWindow = controlP5.addControlWindow("Control Window", 200, 200, 480, 360);

//Initialize Controls slider = controlP5.addSlider("X", 0, 30, 15, 88, 70, 320, 24);

}

//Draw

void draw() {

}``

**Comment by sojamo** [comment]
Did you find a solution for this issue? you wanna share for others to see the solution in the future?

**Comment by smvwhite** [comment]
Hello again
Yes.   I shared the link which had the solution on forums where I was seeking assistance.   Thanks for getting back to  me. 
Regards
Steve
On 1 Jul 2016 7:33 PM, andreas schlegel notifications@github.com wrote:Did you find a solution for this issue? you wanna share for others to see the solution in the future?
