### ISSUE TITLE
midi device not available

### ISSUE THREAD

**Issue by kukovisuals** [sojamo/controlp5#85]
I have read the java receivers and transmitters messages and everything is right i get INs and OUTs from [0] to [13]  with my device name and all, and at the end i get " No Midi device ( SLIDER/KNOB ) is available. "

**Comment by sojamo** [comment]
Is the name of your midi device SLIDER/KNOB? if not, you need to make changes in the code of the example you are referring to. Change the name of the midi device to the name of your midi device.

**Comment by kukovisuals** [comment]
yessss !!! good stuff got it working 👍

**Comment by sojamo** [comment]
question seems to be answered, closing issue.
