### ISSUE TITLE
update multiple Sliders

### ISSUE THREAD

**Issue by p1234321** [sojamo/controlp5#91]
Hello,
First of all thanks for the great library! 
I'm trying to make a small artnet interface with multiple sliders which are expandable.
i create the sliders by:
`

for (int i=0;i<channelArray.length;i++) { 
s = cp5.addSlider("ch"+i,0,255); 
s.setValue(int(channelArray[i])); 
s.setId(i); 
s.setSize(20,100); 
s.setPosition(startPosX+i*offSet,startPosY); 
s.setDecimalPrecision(0); 
}
`
for the beginning i created 16 channels >> 16 sliders, which works well.
but now i want to load different settings from xml files and update the sliders accordingly.
how can i adress the individual sliders via a for loop?

best regards

paul

**Comment by sojamo** [comment]
hi, you can access a controller with cp5.get() and the set the value with setValue()
 
``` Processing
String controllerName = "ch4";
float value = random(100);
cp5.get(controllerName).setValue(value);
```

**Comment by p1234321** [comment]
thank you very much! everything works now!

best regards

paul
_______
paul pritz
hugo-wolf-gasse 10/81
8010 Graz
tel: 06503332443
