### ISSUE TITLE
MidiMapper

### ISSUE THREAD

**Issue by surmvoise** [sojamo/controlp5#96]
Hi there,
I'm really interested in the [MidiMapper](https://github.com/sojamo/controlp5/tree/master/examples/experimental/MidiMapper) example and would love to see this feature in the cp5 library. I'm trying to build a virtual Korg nanoKontrol2 so I can use the sketch even when I don't have the actual controller with me.
I'm not quite familiar with writing java library code but I gave it a try anyway. Is there any news on this feature for cp5? 
Or is there anyone who would help me to develop it in order to implement it in cp5 at some point? Here is my project: https://github.com/surmvoise/MidiMapper-Korg-NanoKONTROL2

**Comment by sojamo** [comment]
Hi, have you looked into the [midimapper library](https://github.com/sojamo/midimapper).

**Comment by surmvoise** [comment]
Oh, I didn't notice this is already a separate library. Cool! 
But how do I install it? It didn't work when I just moved the folder "midimapper" to Processing > libraries. Doesn't it need a "library" folder inside the midimapper folder?

**Comment by sojamo** [comment]
did you use the [latest release](https://github.com/sojamo/midimapper/releases)? When you download the .zip file, the extracted folder will contain the library folder, examples and source code. you need to move the folder _midimapper_ containing these 3 subfolders into Processing's libraries folder.

**Comment by surmvoise** [comment]
Ah, I see. I've only downloaded the repository I guess. Now I managed to install it. Thanks!

**Comment by sojamo** [comment]
@surmvoise can this issue be closed?

**Comment by surmvoise** [comment]
Yes, thanks.
