### ISSUE TITLE
Int turned into float.

### ISSUE THREAD

**Issue by bizkitj** [sojamo/controlp5#99]
Hello, I am not sure if this is bug.
example:  ControlP5slider, the thress sliders are supposed to be int, right? if so, when I 
  `println(cp5.getController("sliderTicks2").getValue());`
put the mark on 127, console is giving me 127.5, mark on 42, console is reading 42.5. 
Is there any way, we can get the exactly  number as it reads on processing window ? e.g mark on 42, console should give 42.

**Comment by sojamo** [comment]
without having checked what you describe, you should be able to cast the returned value into an integer like so `int(cp5.getController("sliderTicks2").getValue());`. .getValue() returns a float, the value calculated by the controller is not rounded.

**Comment by sojamo** [comment]
@bizkitj can this issue be closed?
